### ISSUE TITLE
[Package Request] APX from Vanilla OS

### ISSUE THREAD

**Issue by Heus-Sueh** [ublue-os/packages#24]
I think users will benefit from the ease of apx
https://github.com/Vanilla-OS/apx

Here is his .spec and the copr repository of the creator who made it:
https://download.copr.fedorainfracloud.org/results/champe20/apx/fedora-40-x86_64/06645732-apx/apx.spec
https://copr.fedorainfracloud.org/coprs/champe20/apx/

**Comment by castrojo** [comment]
If there's an existing copr then what's the ask? You could just use the that copr in your image.

**Comment by Heus-Sueh** [comment]
> If there's an existing copr then what's the ask? You could just use the that copr in your image.

Unfortunately, the package offered in the copr repository is not the newest and still has some crashes due to the lack of some dependency, but you can close this issue if there is no interest in maintaining another package among the several that are already maintained here
