### ISSUE TITLE
Add `ffmpegthumbnailer` to the staging repo

### ISSUE THREAD

**Issue by castrojo** [ublue-os/packages#32]
We need https://packages.fedoraproject.org/pkgs/ffmpegthumbnailer/ffmpegthumbnailer/ put in staging for F40.

This will let us move to negativo and off of rpmfusion entirely. F41 blocker.

**Comment by bsherman** [comment]
Per @KyleGospo's suggestion, this didn't even require adding the spec file to our own packages repo... just created the package in our staging COPR and it built clean first try.

https://copr.fedorainfracloud.org/coprs/ublue-os/staging/build/8106992/
