### ISSUE TITLE
Package ublue services

### ISSUE THREAD

**Issue by castrojo** [ublue-os/packages#73]
We have common ublue-* scripts in each image, we should centralize and package them here so that we don't have to modify things in 3 places.

**Comment by ledif** [comment]
After Aurora's split, there has been divergence in the scripts located in `/usr/share/ublue-os` between Bluefin and Aurora. For example, `bluefin-cli` was renamed to `aurora-cli` and the tips in the MOTD have been changed.

Do you envision that we ship multiple packages that are specialized for each image (i.e., `ublue-services-bluefin`, `ublue-services-aurora`) or should we strip out the image-specific stuff and use more generic ublue branding for everything in those scripts?

**Comment by tulilirockz** [comment]
I believe we should ship image-specific things on the image, the ublue scripts should have extensible ways to use them, like adding hooks, variables, stuff like that to make them more generic so we can share them
